version: "2"
services:
  db:
    image: postgres:9.5.1
    environment:
      POSTGRES_USER: "events"
      POSTGRES_PASSWORD: "events"
      POSTGRES_DB: 'events_dev'
  web:
      build: .
      command: bundle exec rails s -p 3000 -b0.0.0.0
      environment:
        PG_HOST: 'db'
        PG_USERID: 'events'
        PG_PASSWORD: 'events'
        PG_DATABASE: 'events_dev'
      volumes:
        - .:/app
      ports:
        - "3000:3000"
      depends_on:
        - db
